"use client"

import { forwardRef } from "react"
import type { ValidationResult } from "@/services/fypIdeas.service"

interface ProposalPrintTemplateProps {
  validation: ValidationResult
}

export const ProposalPrintTemplate = forwardRef<HTMLDivElement, ProposalPrintTemplateProps>(
  ({ validation }, ref) => {
    const { report, title } = validation
    
    if (!report) return null

    return (
      <div 
        ref={ref}
        className="w-[800px] bg-white p-12 text-slate-900"
        style={{ fontFamily: "'Inter', sans-serif" }}
      >
        <div className="border-b-2 border-amber-500 pb-6 mb-8 text-center">
          <h1 className="text-3xl font-bold uppercase tracking-widest text-slate-900">
            Pak-Austria Fachhochschule
          </h1>
          <h2 className="mt-2 text-xl font-medium text-slate-700">
            Institute of Applied Sciences and Technology
          </h2>
          <h3 className="mt-4 text-lg font-semibold text-amber-600 uppercase tracking-wide">
            Final Year Project Proposal
          </h3>
        </div>

        <div className="space-y-8">
          <div>
            <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-2">Project Title</h4>
            <p className="text-2xl font-bold text-slate-900 leading-snug">
              {title || report.plainSummary || "Untitled Project"}
            </p>
          </div>

          <div className="grid grid-cols-2 gap-6 bg-slate-50 p-6 rounded-2xl border border-slate-100">
            <div>
              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Recommendation</h4>
              <p className="font-semibold text-lg text-slate-900">{validation.recommendation || "Pending"}</p>
            </div>
            <div>
              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Final Score</h4>
              <p className="font-semibold text-lg text-amber-600">{report.finalScore}/100</p>
            </div>
          </div>

          {report.elevatorPitch && (
            <div>
              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Proposed Solution & Scope</h4>
              <div className="prose prose-slate max-w-none text-slate-800 leading-relaxed text-justify">
                {report.elevatorPitch}
              </div>
            </div>
          )}

          {report.riskReductionSteps && report.riskReductionSteps.length > 0 && (
            <div>
              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Risk Assessment & Mitigation</h4>
              <ul className="space-y-2">
                {report.riskReductionSteps.map((step, idx) => (
                  <li key={idx} className="flex gap-3 text-slate-800 leading-relaxed">
                    <span className="text-amber-500 font-bold">•</span>
                    <span>{step.replace(/\*\*/g, '')}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {report.roadmap && report.roadmap.length > 0 && (
            <div>
              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Project Implementation Roadmap</h4>
              <div className="space-y-6">
                {report.roadmap.map((phase, idx) => (
                  <div key={idx} className="border-l-2 border-amber-200 pl-4">
                    <h5 className="font-bold text-slate-900 text-lg mb-2">
                      {phase.phase} <span className="text-slate-500 text-sm font-normal ml-2">({phase.duration})</span>
                    </h5>
                    <ul className="space-y-1">
                      {phase.tasks.map((task, taskIdx) => (
                        <li key={taskIdx} className="text-slate-700 text-sm flex gap-2">
                          <span className="text-slate-400">-</span>
                          <span>{task.replace(/\*\*/g, '')}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
        
        <div className="mt-16 pt-8 border-t border-slate-200 text-center text-sm text-slate-400">
          Generated by FYP Finder AI Validator
        </div>
      </div>
    )
  }
)
ProposalPrintTemplate.displayName = "ProposalPrintTemplate"
